### ISSUE TITLE
Add instructions on how to install this addon

### ISSUE THREAD

**Issue by BeayemX** [OrigamiDev-Pete/TODO_Manager#1]
It would be nice to have instructions in the readme on how to put this addon in one's project.

Even if it just says to copy the files into a Godot project.
This would help new developers getting started and probably increase the number of people who will try and use this project.

Also information regarding if the addon has to be in a specific directory.

**Comment by demwilson** [comment]
Even a link to the [official Godot installing plugins](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/installing_plugins.html) page would suffice.

**Comment by OrigamiDev-Pete** [comment]
You're right. Thanks for the suggestion 🙂
