### ISSUE TITLE
Add an option to ignore files from addons

### ISSUE THREAD

**Issue by hilfazer** [OrigamiDev-Pete/TODO_Manager#10]
title

**Comment by OrigamiDev-Pete** [comment]
I believe this is possible by using the 'Ignore Paths' box in the settings tab.

![101417127-d9f73f80-38f3-11eb-922b-e7629049e336](https://user-images.githubusercontent.com/55121683/113502555-5af7d800-9570-11eb-898f-dac7b5ab2d6f.gif)

**Comment by hilfazer** [comment]
Oops! Yes, it is. I was using version 1.0.
