### ISSUE TITLE
Todo-Manager, feature request: Scan c-files too

### ISSUE THREAD

**Issue by pink-ink** [OrigamiDev-Pete/TODO_Manager#12]
Dear Peter,

Thanks for this plugin, I love it!
I'm using GDNative to add c-code to my Godot project and I would like Todo-Manager to scan c-files too and show their TODOs.
How/where can this be done in the code?
(I've looked through it but didn't find where you search for *.gd files).

Best,
Joerg

**Comment by OrigamiDev-Pete** [comment]
Hi Joerg,

Thanks for using my plugin! The place where the plugin decides which files to parse is on line 197 of plugin.gd. If you would like to add other file types for your own project then it should be as simple as adding an additional or statement that is `file_name.ends_with(".c")`  (or whatever file extensions you want).

Hope that helps!

**Comment by pink-ink** [comment]
Hi Peter,

thank you very much for your help!

I've changed line 197 like this:
`			if file_name.ends_with(".gd") or file_name.ends_with(".cs") or file_name.ends_with(".c") or file_name.ends_with(".cpp") or file_name.ends_with(".h") or (file_name.ends_with(".tscn") and _dockUI.builtin_enabled):
`
Now the c, cpp and h-files also show up in the list, yeah!

One thing doesn't work yet. When I click on the todo line, shown in the list, the c, cpp and h-files don't open up. The right line is selected, but in the previously opened file. It seems the line is calculated correctly, but the file does not load yet. Do you have a clue why?

**Comment by OrigamiDev-Pete** [comment]
Hi Joerg,
I just added external editor support for VSCode, Rider, Atom and Sublime. I also added the .c, .cpp, and .h check into the main branch so you shouldn't need to change the plugin.gd code again.
Let me know how you go. I'll submit the update to the AssetLib soon but until then feel free to download directly from github to try it out.

**Comment by pink-ink** [comment]
Hi Peter,
that's perfect, thank you very much. 👏👏👏
