### ISSUE TITLE
Can't open TODO item in vscode

### ISSUE THREAD

**Issue by luis-gmonkey** [OrigamiDev-Pete/TODO_Manager#13]
When I try to open a TODO item from godot instead of opening the desired script in the current line, the vscode just creates a new  file named `my_script.gd:100`

![Screenshot_20210817_121700](https://user-images.githubusercontent.com/54543087/129716902-264f943b-2b3a-4b07-b331-bbdccc87eb88.png)

My settings for the external editor are 
Exec Path `code`
Exec Flags `{project} --goto {file}:{line}:{col}`

How can I fix this?

**Comment by OrigamiDev-Pete** [comment]
Hi Luis,
My thought is that your external editor path is pointing to Code.exe rather than Code.cmd which is the recommendation of the docs https://docs.godotengine.org/en/stable/getting_started/editor/external_editor.html

Without pointing to code.cmd the plug-in uses different flags.

Let me know if that's the problem.
Thanks!

**Comment by luis-gmonkey** [comment]
I'm using Linux so I don't have those, I just have the command code. But now I tested with another editor (kate) and works flawlessly.

**Comment by OrigamiDev-Pete** [comment]
Right. I was silly and forgot about Linux when adding external editors.
Thanks for alerting me to this! I'll fix this up soon.
In the mean time, if you would like it to work with VScode you should only need to change line 94 in Dock.gd to be endswith("code").

Let me know how you go

**Comment by luis-gmonkey** [comment]
Yep that fixes it :)
Maybe you could just split the string with "."  and only use the first index or you could  just add to settings tab an input to customize flags, with some presets for some editors.

Thank you very much for this plugin :)

**Comment by luis-gmonkey** [comment]
I added #14 , not my proudest code so feel free to discard it  :sweat_smile:

**Comment by OrigamiDev-Pete** [comment]
Thanks for your help!
For now I've just implemented it using an extra comparison statement for the sake of simplicity.
I don't have a system running a Linux OS at the moment so if you have the opportunity to try out the latest commit let me know if it works correctly.

**Comment by luis-gmonkey** [comment]
I just tested your commit and it works pretty well :+1: 

Btw do you if it's possible to update the plugin using godot, I'm guessing that it will not update alone right?

**Comment by OrigamiDev-Pete** [comment]
Great! Thanks for all your help
Unfortunately the Godot Asset Library doesn't have a seamless update system yet so you'll have to update manually for now. I'll be adding the patch to the Asset Library today so hopefully it will be there soon as well.

**Comment by luis-gmonkey** [comment]
Thank you for your plugin.
