### ISSUE TITLE
Sort files alphabetically

### ISSUE THREAD

**Issue by lexum0** [OrigamiDev-Pete/TODO_Manager#18]
Currently they are shown in apparent random order, alphabetical filename sorting would greatly help find TODOs

**Comment by OrigamiDev-Pete** [comment]
Hi,
Thanks for notifying me that the alphabetic sorting wasn't working correctly. I accidently had it backwards.
Until now the sorting was based on the full path of the file which mean that scripts within the same directories would be grouped together.

I just added sorting based on the script name in the latest commit. You can now choose between sorting by file path or script name depending on the 'Script Name' option in the settings.

Hope this helps! I'll update the release in the Godot Asset Library soon. Until then you can clone the files from the repository.
Let me know how you go.
