### ISSUE TITLE
Move example scripts into separate folder

### ISSUE THREAD

**Issue by BeayemX** [OrigamiDev-Pete/TODO_Manager#2]
The scripts `example.gd` and `2.gd` could be moved into an `example` folder.
This way it is easier to see which files are not necessary for the plugin to work and they can be ignored in the importing process.

**Comment by OrigamiDev-Pete** [comment]
Woops! 2.gd isn't even never to be there haha. I was thinking about whether having an example script is worth it or if it's just annoying for regular users. 
It's a good idea to move it out from the source code folder though.
