### ISSUE TITLE
[Godot 4 Beta 1] TODO Tab not opening

### ISSUE THREAD

**Issue by lukiono** [OrigamiDev-Pete/TODO_Manager#21]
Greetings, 

In the newest Beta 1 version from Godot 4 the TODO Tab at the Bottom doesnt open.

Screenshot:
![ToDoManager_B1](https://user-images.githubusercontent.com/831436/190671030-9f2a72e1-7c2b-42b6-b41b-36e6ae81e06c.png)

Error(s) in Logfile:
res://addons/Todo_Manager/Project.gd:43 - Invalid call. Nonexistent function 'set_tooltip' in base 'TreeItem'.
res://addons/Todo_Manager/Dock.gd:142 - Invalid call. Nonexistent function 'raise' in base 'Button'.

Kind regards

**Comment by OrigamiDev-Pete** [comment]
Thanks for letting me know. I'll look into this soon.

**Comment by OrigamiDev-Pete** [comment]
These issues should be addressed in the latest commit (7e744b3).
