### ISSUE TITLE
[Feature] adding notes

### ISSUE THREAD

**Issue by TandersT** [OrigamiDev-Pete/TODO_Manager#23]
I suggest adding a 4th label for notes, I.e. in my case I wish to save a link I use for some handling of 3D models, and it would be ideal to have that link inside this tab. It would be against the name of the addon though.

**Comment by OrigamiDev-Pete** [comment]
Hi!
Thanks for your suggestion, though I think this may be outside the scope of this addon.
Perhaps you could make a custom tag for notes?
