### ISSUE TITLE
unable to enable the plugin (Godot 4)

### ISSUE THREAD

**Issue by Hunam6** [OrigamiDev-Pete/TODO_Manager#25]
When I tick "Enable" I get this error:
```
Unable to load addon script from path: 'res://addons/Todo_Manager/plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/Todo_Manager/plugin.cfg' to prevent further errors.
```

**Comment by OrigamiDev-Pete** [comment]
Hi there,
What version of the Godot 4 beta are you using when you get this error?

**Comment by Hunam6** [comment]
Woops I forgot to include the extact version, I'm running on Godot 4 beta 4.

**Comment by OrigamiDev-Pete** [comment]
Thanks, I'll look into this soon.

**Comment by Hunam6** [comment]
I found the issue, I've installed your plugin via the AssetManager. But the latest release you published doesn't include the last commits. And I guess that when you install plugins via the AssetManager it installs the latest Github release.
I tried cloning the repo manually (from the latest commit then) and it worked!

**Comment by OrigamiDev-Pete** [comment]
Ah well spotted! I must have forgotten to publish the latest version to the asset library.
Thanks for investigating and thanks for using Todo Manager!

**Comment by Hunam6** [comment]
Thank you for making this absolutely necessary plugin!
