### ISSUE TITLE
Failed rescan

### ISSUE THREAD

**Issue by git2013vb** [OrigamiDev-Pete/TODO_Manager#26]
If you delete a file where there are TODO's it fail to rescan (TODO tab) and it freeze the editor
Godot 4

Also if you click in any TODO in tab it will open the vscode at the right row but the editor freeze after clik

I have to restart it.

Thanks

**Comment by OrigamiDev-Pete** [comment]
Hi there, just a few follow up questions.

Are there any errors in the console/output before the freeze?
Does this happen when using Godot's internally editor, or only when using external (vscode)?

**Comment by git2013vb** [comment]
I use this build 
v4.0.beta.custom_build [57267709e]
No errors but maybe it depends because it freeze?
It happen only when I use vscode.

**Comment by OrigamiDev-Pete** [comment]
Thanks for the info. Also, what version of TODO Manager are you using?

**Comment by git2013vb** [comment]
> Thanks for the info. Also, what version of TODO Manager are you using?

The one from assetlib (Godot 4)

**Comment by OrigamiDev-Pete** [comment]
I'm having trouble reproducing this bug in Godot 4 beta 10. Maybe there's something funny in the most recent Godot commits. I'll keep an eye on this, especially when beta 11 comes out in case there's a regression.

**Comment by git2013vb** [comment]
No problem , its not urgent :) take your time.

**Comment by OrigamiDev-Pete** [comment]
Issue #27 maybe be related to this. Currently investigating changes in Godot 4 beta 11.

**Comment by OrigamiDev-Pete** [comment]
Closing this under the assumption that Godot 4 beta 12 has fixed this issue.
