### ISSUE TITLE
Godot 4 Rc1 -  Array invalid type

### ISSUE THREAD

**Issue by DeadlyEssence01** [OrigamiDev-Pete/TODO_Manager#30]
Loading up a project with Godot 4 RC1 gives this error in the editor: 

` res://addons/Todo_Manager/plugin.gd:230 - Invalid type in function 'combine_patterns' in base 'EditorPlugin ()'. The array of argument 1 (Array) does not have the same element type as the expected typed array argument.`

This seems to prevent TODO Manager from running correctly.

Please let me know if you need additional information.

**Comment by OrigamiDev-Pete** [comment]
Thanks for letting me know. I'll look into this soon.

**Comment by OrigamiDev-Pete** [comment]
I don't seem to be able to recreate this error on RC1 or RC2. Are you running the latest version of the plugin?

**Comment by DeadlyEssence01** [comment]
I deleted and reinstalled the plugin on RC1 and still had the issue, on two separate machines (but the same project) but the error is gone on RC2, so I'll just use the most recent version. I can try and sus out the problem if necessary, but given it is resolved now, I don't mind just closing the issue. 

Thanks!

**Comment by OrigamiDev-Pete** [comment]
Great, let me know if it pops up again. It's definitely related to the GDScript changes they made in the last few betas so it's probably a little wobbly still. I'll reopen if necessary.
