### ISSUE TITLE
Case-sensitivity

### ISSUE THREAD

**Issue by KoB-Kirito** [OrigamiDev-Pete/TODO_Manager#31]
Gread addon!
Could you add an option, or make it the default, that it doesn't check for case-sensitivity?

Edit: Got it working by prepending (?i) to your compiles, for example regex.compile("(?i)" + pattern[0]).

**Comment by OrigamiDev-Pete** [comment]
Hi there,
Thanks for enjoying the plugin!
Great idea. I've just added a case sensitivity checkbox to the settings.
![image](https://user-images.githubusercontent.com/55121683/223581948-6a966f3a-0dfc-41a1-9275-9073a405aa38.png)

Let me know how it goes.
It will be included in the v2.2.0 release in the asset library soon, or you can test it from repo.
