### ISSUE TITLE
Enabling plugin doesn't give functionality

### ISSUE THREAD

**Issue by boyAdjacent** [OrigamiDev-Pete/TODO_Manager#38]
Installed the plugin via the Asset Library according to instructions here. When enabling the plugin via project settings, the TODO tab never opens up, and output gives this error
' ' '
  res://addons/Todo_Manager/plugin.gd:28 - Trying to assign value of type '' to a variable of type 'Dock.gd'.
' ' '
using 4.2.1

**Comment by OrigamiDev-Pete** [comment]
Hi!
I just had a go at installing via the Asset Library on 4.2.1 and I couldn't replicate this behaviour. Do you have any other plugins also installed?

**Comment by boyAdjacent** [comment]
I also have Qodot 2023.2.alpha installed and enabled

**Comment by boyAdjacent** [comment]
Upon relaunching the editor a few days later, the plugin seems to be working without issue! Thanks!

**Comment by OrigamiDev-Pete** [comment]
How strange! Something to keep an eye on 🤔
