### ISSUE TITLE
It is recommended to add "class_name" to the class to adapt to the new version of Godot.

### ISSUE THREAD

**Issue by TheOneImmortal** [OrigamiDev-Pete/TODO_Manager#39]
This addons can't run on **godot 4.2.1.stable**.

To make it work on the **4.2.1.stable**.
Add `class_name` keyword.

For example:
```
old :
@tool
extends Panel

new :
@tool
class_name TodoProject
extends Panel
```

Files that need to be modified include:
- Current.gd
- Dock.gd
- Project.gd
- todoItem_class.gd
- todo_class.gd

**Comment by OrigamiDev-Pete** [comment]
It appears to run fine for me on version 4.2.1. I'd prefer to avoid using `class_name` where possible so as to not pollute the user's class lists.
