### ISSUE TITLE
For builtin, the line number not correct.

### ISSUE THREAD

**Issue by CsloudX** [OrigamiDev-Pete/TODO_Manager#40]
![image](https://github.com/OrigamiDev-Pete/TODO_Manager/assets/35988767/64eddd3f-552b-446d-979a-f16423e42aa9)

**Comment by OrigamiDev-Pete** [comment]
Funnily enough, the search panel also has this problem and it doesn't seem to navigate to the file when you click on it 🙃.
![image](https://github.com/OrigamiDev-Pete/TODO_Manager/assets/55121683/7288b532-eb41-4a35-8af7-c77348dad0f3)

This commit 67d1547 improves built-in support.
- Line numbers are now correct.
- Double clicking on a built-in todo now opens the file and jumps to the line
- The 'Current' tab now supports built-in scripts.

There is a speed cost associated with scanning built-in scripts so it will still be off by default but I hope these improvements are useful 😊

**Comment by OrigamiDev-Pete** [comment]
I just submitted a new version with these changes to the asset library. It should be available in the next few days. Until then feel free to clone from the repo 😊
