### ISSUE TITLE
Add user-defined comment prefixes

### ISSUE THREAD

**Issue by orgrinrt** [OrigamiDev-Pete/TODO_Manager#5]
I've written a hacky workaround for my own use, but I thought this could be a useful feature for the plugin that could warrant some thinking and discussion.

So, currently I think the plugin is hard-coded to look for comment lines starting with `#` as in gdscript (either that or I messed something up on my end). As C# is a first-class citizen in godot, it would make sense to support it out-of-box (the `//` syntax).

But then I realized I personally use multi-line comments quite often (`/* ... */` syntax), so I got to thinking that there probably are gdnative bindings for languages that have more differing syntax for this (assuming they are accessible with the godot filesystem).

So maybe it would be better to include a field in the config for this, something like "Comment prefixes" or similar, and iterate over those when building the regex filter. Also provide a sensible default for gdscript and csharp so most users wouldn't have to touch it or think about it.

Right now I made a dirty workaround by hard-coding the C# syntax like so:

```
# plugin.gd, line 183 -->

for i in range(patterns.size()):
	if i == 0:
		pattern_string = "#\\s*" + patterns[i][0] + ".*" <-- the original filter
		pattern_string += "|" + "//\\s*" + patterns[i][0] + ".*" <-- hacky addition
		pattern_string += "|" + "/*\\s*" + patterns[i][0] + ".*" <-- hacky addition
	else:
		pattern_string += "|" + "#\\s*" + patterns[i][0]  + ".*"
		pattern_string += "|" + "//\\s*" + patterns[i][0]  + ".*"
		pattern_string += "|" + "/*\\s*" + patterns[i][0]  + ".*"
return pattern_string
```

It seems to work adequately (note that I'm not very familiar with regex, so it's probably not a good way to go about it anyway), but it's not very nice to look at and definitely would get cumbersome if the plugin wanted to include any more different kinds of comment notations. So it would probably make sense to have a user-defined array of prefixes to dynamically add to these filters.

I didn't want to go ahead and make a PR just yet because A) I'm not sure if this would be all that useful and B) not sure how it should be interfaced with, i.e what's the ux going to be in the config view.

Note that this is based on version 1.0.3 so not sure if this got changed/fixed recently. If that's the case, feel free to disregard and close this.

If this is something that would be useful, I don't mind writing it, just didn't want to jump the gun and waste effort.

**Comment by OrigamiDev-Pete** [comment]
This was something I considered early on when I was making the plugin but my assumption at the time was that the majority of people using C# where more likely to use an external editor like VScode or Rider which already have TODO lists so I decided against it.
That said, you're right about C# being first-class in Godot so it could be worth considering again. I had a go at seeing what a regex pattern that incapsulated all of those options might look like and I came up with this.

`((\/\*)|(#|\/\/))\s*\bTODO\b(?(2)[\s\S]*?\*\/|.*)`

You can see it in action here: https://regex101.com/r/wU7zB2/179
I'm not 100% sure if Godot handles conditional Regex but if it does then I think it could be as simple as replacing the regex pattern and making the plugin look for .cs files as well as .gd. 
The multi-line comments may take a little configuring to display similarly to how @SIsilicon added in #4.

I'm more than happy for you to have a go and I'll help out where I can if you need.

**Comment by OrigamiDev-Pete** [comment]
As far as user defined comment tokens go I'm not so sure. The `//`, `#`, and `/**/` tokens cover the majority of languages and anything other than C# or GDScript probably wouldn't be used in the Godot editor. It probably would be more complicated than it's worth to include something like that.

**Comment by OrigamiDev-Pete** [comment]
C# support has been integrated into main via #6

**Comment by orgrinrt** [comment]
Ah, I missed the chance, spent the holiday season away from work. But good addition I would say, even if people often use 3rd party todo managers in C# it's often convenient to have some TODO/HACK items in C# source displayed to the designers as well in the godot editor.

Should have mentioned that I would be able to take a catch of this after the holidays, I hope it didn't cause any annoyance!

**Comment by OrigamiDev-Pete** [comment]
No problem at all. I was planning on leaving it to you but I had a free day and it ended up being pretty simple to implement. It also made a nice addition to a version 1.1 release so thanks for the suggestion.

I have an idea for the next major release involving Trello-style Kanban boards. I'll try to mock up a proposal and it would be great to get your feedback if you're interested.

**Comment by orgrinrt** [comment]
Yeah I imagine it was just extending the regex, since if I recall correctly the plugin already searched for .cs files.

I'd be happy to if I have the time! That is a great idea by the way. Looking forward to it.
