### ISSUE TITLE
Debug print statements "timer" and "this" should maybe be removed?

### ISSUE THREAD

**Issue by Arnklit** [OrigamiDev-Pete/TODO_Manager#7]
Love the TODO manager, but I noticed that while using it there is stuff printed in my console output like:

this
here
timer
...

Looks to be some debug print statement. Every time you select settings it prints the "this" line for example.

**Comment by OrigamiDev-Pete** [comment]
Thanks for using TODO Manager! I believe all the debug prints were removed in the latest version 1.1 release. Please try out that version and let me know if anything continues to print.

**Comment by Arnklit** [comment]
Ah that's great. I should have thought about checking master. Thanks Pete! And happy new year :).
